services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      SECRET_KEY: change-me
      JWT_SECRET_KEY: change-me-too
      SEED_DEFAULT_DATA: "true"
    volumes:
      - flask_instance:/app/instance
    restart: unless-stopped

volumes:
  flask_instance:
